### PR TITLE
ENH: Update CI for ITK 5.2.0.post2

### PR DESCRIPTION
**Pull request by tbirdso**
From #19

### CODE REVIEW

**Comment by tbirdso** [comment]
Seeing symlink issue for macOS Python package build: 
> brew install ninja

>Error: The `brew link` step did not complete successfully
The formula built, but is not symlinked into /usr/local
Could not symlink bin/2to3
Target /usr/local/bin/2to3
already exists. You may want to remove it:
  rm '/usr/local/bin/2to3'

> To force the link and overwrite all conflicting files:
  brew link --overwrite python@3.9

> To list all files that would be deleted:
  brew link --overwrite --dry-run python@3.9

**Comment by tbirdso** [comment]
@thewtex Have you seen this failure before with `itk==v5.2.0.post2`? Seeing a `brew` failure on macos when attempting upgrade to `5.2.0.post2` which is resolved by downgrading requirements back to `5.2.0`. Failure doesn't seem to be present in any other build.

**Comment by thewtex** [comment]
@tbirdso seems to have failed in one build:

https://github.com/InsightSoftwareConsortium/ITKModuleTemplate/actions/runs/817087555

but passed in another:

https://github.com/InsightSoftwareConsortium/ITKModuleTemplate/actions/runs/817087556

please try re-building.

**Comment by tbirdso** [comment]
@thewtex Attempted rebuilding a couple of times, but no luck building for `v5.2.0.post2` on macOS. Continue to see `brew link` failures:
> Error: The `brew link` step did not complete successfully

Seeing an identical error message in [`ITKModuleTemplate`](https://github.com/InsightSoftwareConsortium/ITKModuleTemplate/runs/2518884701) although the build seems to run longer before exit.

Comparing with the most recent successful build in [`ITKModuleTemplate`](https://github.com/InsightSoftwareConsortium/ITKModuleTemplate/runs/2514925879?check_suite_focus=true), it looks like the failing builds are possibly building against Python 3.9 while the successful build built against Python 3.8.9?

From successful build:
> ==> Upgrading python@3.8 3.8.9 -> 3.8.10 

From failing builds:
> ==> Installing ninja dependency: python@3.9
==> Pouring python@3.9--3.9.5.catalina.bottle.tar.gz
Error: The `brew link` step did not complete successfully

Let me know if you would rather I enter an issue against `ITKModuleTemplate` as it doesn't seem to be limited to `ITKShape`.

**Comment by tbirdso** [comment]
Should also note we're now seeing `build-linux-python-packages` failures in this PR that weren't present yesterday, doesn't look like CI has run on `ITKModuleTemplate` today so no information yet on whether this is an isolated issue.

**Comment by tbirdso** [comment]
Pushed with altered commit message to rerun CI.

**Review by thewtex — APPROVED** [review]
Thanks @tbirdso !

**Pull request merged**
